# server name
s3_cluster:
    # volume type: s3 or s3v2
    type: s3
    # s3 endpoint
    endpoint: http://127.0.0.1:8000
    # bucket region
    region: us-east-1
    # path-style access, required for MinIO
    path_style_access: true
    # access key (USER MAPPING option)
    access_key_id: admin
    # secret key (USER MAPPING option)
    secret_access_key: password
    # optional bucket name, usually given in the DDL instead
    # bucket_name: warehouse
