-- Regression test for Sonic Hash Join routing in the vectorization engine.
--
-- When a HashJoin node has a sonic-compatible join type and both sides are
-- PAX tables, BuildHashjoin (execMain.c) routes it to Arrow's SonicJoinNode
-- (cpp/src/arrow/compute/exec/sonic_join_node.cc); otherwise it falls back
-- to the legacy Arrow HashJoin.  Coverage:
--
--   contrib/vectorization/src/backend/vecexecutor/execMain.c
--     sonic_join_supports_jointype / is_sonic_join_compatible / BuildHashjoin
--   contrib/vectorization/src/backend/hook/explain.c
--     "Vec Hash Join Method:  Sonic" line in EXPLAIN VERBOSE
--
-- Supported join types (sonic_join_supports_jointype):
--   INNER, LEFT/RIGHT OUTER, FULL OUTER,
--   LEFT_SEMI, LEFT_ANTI, RIGHT_SEMI, RIGHT_ANTI.
-- Not routed: LASJ_NOTIN (NOT IN with possibly-NULL subquery column).
--
-- Test data:
--   hj_big   1000 rows  id 1..1000    (large PAX table, distributed by id)
--   hj_small   20 rows  id 991..1010  (small PAX table, distributed by id)
--   Overlap: id 991..1000 (10 rows); only-in-small: id 1001..1010 (10 rows).
--
-- RIGHT SEMI / RIGHT ANTI are only generated by ORCA (optimizer = on); there
-- is no GUC to force them (the old optimizer_force_hash_semijoin does not
-- exist on this codebase's ORCA).  ORCA's cost model naturally picks the
-- right-flipped physical join when the outer side (hj_small, 20 rows) is
-- much smaller than the inner side (hj_big, 1000 rows) -- the same
-- small-outer/large-inner shape used by the existing
-- join_gp_optimizer.out "GUC enable_hashagg takes effect for SEMI join"
-- test.  All other join types are tested with optimizer = off for
-- plan-shape stability.

SET vector.enable_vectorization = on;
SET vector.enable_sonic_hashjoin = on;
SET default_table_access_method = pax;
SET optimizer = off;

DROP SCHEMA IF EXISTS vec_sonic_hj CASCADE;
CREATE SCHEMA vec_sonic_hj;
SET search_path = vec_sonic_hj;

CREATE TABLE hj_big   (id int NOT NULL, val int) DISTRIBUTED BY (id);
CREATE TABLE hj_small (id int NOT NULL, val int) DISTRIBUTED BY (id);

INSERT INTO hj_big   SELECT i, i * 2       FROM generate_series(1,    1000) i;
INSERT INTO hj_small SELECT i, i * 3       FROM generate_series(991,  1010) i;
ANALYZE hj_big;
ANALYZE hj_small;

-- Force hash join in the legacy planner so EXPLAIN output is stable.
SET enable_nestloop = off;
SET enable_mergejoin = off;

-- ------------------------------------------------------------------
-- A) Routing: optimizer = off.
--    Verify "Vec Hash Join Method:  Sonic" for the join types the legacy
--    planner generates: INNER, LEFT SEMI (EXISTS), LEFT ANTI (NOT EXISTS).
-- ------------------------------------------------------------------

-- A1: INNER JOIN
EXPLAIN (VERBOSE ON, COSTS OFF)
SELECT hj_big.id
FROM hj_big
JOIN hj_small ON hj_big.id = hj_small.id;

-- A2: LEFT SEMI (EXISTS)
EXPLAIN (VERBOSE ON, COSTS OFF)
SELECT hj_big.id
FROM hj_big
WHERE EXISTS (SELECT 1 FROM hj_small WHERE hj_small.id = hj_big.id);

-- A3: LEFT ANTI (NOT EXISTS)
EXPLAIN (VERBOSE ON, COSTS OFF)
SELECT hj_big.id
FROM hj_big
WHERE NOT EXISTS (SELECT 1 FROM hj_small WHERE hj_small.id = hj_big.id);

-- A4: Normal fallback when sonic is disabled.
--    Node name stays "Vec Hash Join" but method line should read "Normal".
SET vector.enable_sonic_hashjoin = off;
EXPLAIN (VERBOSE ON, COSTS OFF)
SELECT hj_big.id
FROM hj_big
JOIN hj_small ON hj_big.id = hj_small.id;
SET vector.enable_sonic_hashjoin = on;

RESET enable_nestloop;
RESET enable_mergejoin;

-- ------------------------------------------------------------------
-- B) Routing: optimizer = on, small outer (hj_small) / large inner (hj_big).
--    RIGHT SEMI / RIGHT ANTI are only generated by ORCA; verify they
--    also show "Vec Hash Join Method:  Sonic".
-- ------------------------------------------------------------------

SET optimizer = on;

-- B1: RIGHT SEMI — small outer IN (SELECT ... FROM big).
--    ORCA picks Right Semi Hash Join when the outer table is smaller.
EXPLAIN (VERBOSE ON, COSTS OFF)
SELECT hj_small.id
FROM hj_small
WHERE hj_small.id IN (SELECT id FROM hj_big);

-- B2: RIGHT ANTI — small outer NOT EXISTS big.
EXPLAIN (VERBOSE ON, COSTS OFF)
SELECT hj_small.id
FROM hj_small
WHERE NOT EXISTS (SELECT 1 FROM hj_big WHERE hj_big.id = hj_small.id);

SET optimizer = off;

-- ------------------------------------------------------------------
-- C) Correctness: INNER JOIN
--    10 matching rows (id 991..1000).
-- ------------------------------------------------------------------

SELECT hj_big.id, hj_big.val, hj_small.val AS small_val
FROM hj_big
JOIN hj_small ON hj_big.id = hj_small.id
ORDER BY hj_big.id;

-- ------------------------------------------------------------------
-- D) Correctness: semi / anti variants (optimizer = off)
--    Expected: LEFT SEMI 10 rows, LEFT ANTI 990 rows, EXISTS 10 rows.
-- ------------------------------------------------------------------

-- D1: IN subquery — same result as EXISTS (LEFT SEMI path)
SELECT count(*) AS c
FROM hj_big
WHERE hj_big.id IN (SELECT id FROM hj_small);

-- D2: NOT EXISTS (LEFT ANTI) — 990 rows (id 1..990)
SELECT count(*) AS c
FROM hj_big
WHERE NOT EXISTS (SELECT 1 FROM hj_small WHERE hj_small.id = hj_big.id);

-- D3: EXISTS (LEFT SEMI) — 10 rows (id 991..1000)
SELECT count(*) AS c
FROM hj_big
WHERE EXISTS (SELECT 1 FROM hj_small WHERE hj_small.id = hj_big.id);

-- ------------------------------------------------------------------
-- E) Correctness: RIGHT SEMI / RIGHT ANTI (optimizer = on,
--    small outer hj_small / large inner hj_big)
--    Expected: RIGHT SEMI 10 rows (id 991..1000 match big),
--              RIGHT ANTI 10 rows (id 1001..1010 not in big).
-- ------------------------------------------------------------------

SET optimizer = on;

-- E1: RIGHT SEMI — 10 rows (hj_small ids that exist in hj_big)
--     EXPLAIN first: a count(*) wrapper can make ORCA pick a different
--     decorrelation strategy than the bare SELECT in B1, so confirm this
--     exact (aggregated) query shape still routes through Right Semi +
--     Sonic before trusting the count below.
EXPLAIN (VERBOSE ON, COSTS OFF)
SELECT count(*) AS c
FROM hj_small
WHERE hj_small.id IN (SELECT id FROM hj_big);

SELECT count(*) AS c
FROM hj_small
WHERE hj_small.id IN (SELECT id FROM hj_big);

-- E2: RIGHT ANTI — 10 rows (hj_small ids not in hj_big)
EXPLAIN (VERBOSE ON, COSTS OFF)
SELECT count(*) AS c
FROM hj_small
WHERE NOT EXISTS (SELECT 1 FROM hj_big WHERE hj_big.id = hj_small.id);

SELECT count(*) AS c
FROM hj_small
WHERE NOT EXISTS (SELECT 1 FROM hj_big WHERE hj_big.id = hj_small.id);

SET optimizer = off;

-- ------------------------------------------------------------------
-- F) Edge cases: empty build table
-- ------------------------------------------------------------------

CREATE TABLE hj_empty (id int NOT NULL, val int) DISTRIBUTED BY (id);
ANALYZE hj_empty;

-- F1: INNER JOIN with empty build → 0 rows
SELECT count(*) AS c
FROM hj_big JOIN hj_empty ON hj_big.id = hj_empty.id;

-- F2: LEFT ANTI with empty build → all 1000 rows pass
SELECT count(*) AS c
FROM hj_big
WHERE NOT EXISTS (SELECT 1 FROM hj_empty WHERE hj_empty.id = hj_big.id);

-- F3: LEFT SEMI with empty build → 0 rows
SELECT count(*) AS c
FROM hj_big
WHERE EXISTS (SELECT 1 FROM hj_empty WHERE hj_empty.id = hj_big.id);

-- F4: INNER JOIN with empty probe → 0 rows
SELECT count(*) AS c
FROM hj_empty JOIN hj_big ON hj_empty.id = hj_big.id;

-- ------------------------------------------------------------------
-- G) Edge cases: NULL keys in join column
--    NULLs must not match any row (equijoin semantics).
-- ------------------------------------------------------------------

CREATE TABLE hj_nulls (id int, val int) DISTRIBUTED RANDOMLY;
INSERT INTO hj_nulls VALUES (NULL, 1), (NULL, 2), (1, 3), (2, 4);
ANALYZE hj_nulls;

-- G1: INNER JOIN — only id=1 and id=2 match (2 rows)
SELECT count(*) AS c
FROM hj_big JOIN hj_nulls ON hj_big.id = hj_nulls.id;

-- G2: LEFT SEMI — big rows with id=1 or id=2 match (2 rows)
SELECT count(*) AS c
FROM hj_big
WHERE EXISTS (SELECT 1 FROM hj_nulls WHERE hj_nulls.id = hj_big.id);

-- G3: LEFT ANTI — 998 big rows have no match (NULLs do not match)
SELECT count(*) AS c
FROM hj_big
WHERE NOT EXISTS (SELECT 1 FROM hj_nulls WHERE hj_nulls.id = hj_big.id);

-- ------------------------------------------------------------------
-- Cleanup
-- ------------------------------------------------------------------

SET search_path = public;
DROP SCHEMA vec_sonic_hj CASCADE;
RESET optimizer;
RESET vector.enable_sonic_hashjoin;
RESET default_table_access_method;
RESET vector.enable_vectorization;
